name: Rust

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        cargo-args:
          - build
          - fmt --check
          - clippy --all-targets -- -D clippy::all
          - bench
          - doc
          - test
    runs-on: ubuntu-latest
    
    steps:
    - name: Install packages
      run: sudo apt-get install libllvm18 llvm-18 llvm-18-dev libpolly-18-dev
    - uses: Swatinem/rust-cache@v2
    - name: Run checks
      env:
        RUSTFLAGS: -D warnings
        RUSTDOCFLAGS: -D warnings
      run: |
        cargo ${{matrix.cargo-args}}
